### ISSUE TITLE
Learn.sumary() error in 06-Object_detection.ipynb notebook

### ISSUE THREAD

**Issue by DaraSamii** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#42]
Hi
in the Practical-Deep-Learning-for-Coders-2.0, in the Computer Vision Folder, notebook 06_Object_detection.ipynb after creating
learner , executing `learn.summary()` raises an error.
in `learn.predict `, `learn.show_results` and `learn.get_preds` the same error raises. 
Please help.
![image](https://user-images.githubusercontent.com/49064863/130334847-e11d2311-5a77-487a-af0d-779d95964dc1.png)

**Comment by DaraSamii** [comment]
Note that I used this two versions of fastai and fastcore with out them. and with full updated fastai the learn = Learner(...) raises an error too!
"fastcore==1.3.2"
"fastai>2,<2.1"

**Comment by muellerzr** [comment]
What is your version of fastai? You need the version of fastai that goes with the fastcore version for things to not break. Ex fastcore is currently at 1.3.26. The fastai version likely to work with 1.3.2 is fastai version 2.1.4 or 2.1.5, which is quite outdated.

**Comment by DaraSamii** [comment]
I have tried all fastai and fastcore versions in all of them this specific error raised. from fastai==2.0.0 upto fastai==2.5.2 and all fastcores. I noticed the notebook has been puplished on Aug 2020 so I revised the fastai and fastcore to that date and but again this error raised.
I Saw the tutorial page and saw this:
![image](https://user-images.githubusercontent.com/49064863/130357168-c37ff660-4d58-4d9f-a5cc-32db5039f626.png)
anth the link: https://walkwithfastai.com/Object_Detection
I wanted to know is this problem solved?

**Comment by muellerzr** [comment]
I'll try running it later today.

**Comment by muellerzr** [comment]
First, please do note that really this questions should be on the walk with fastai repo, https://github.com/walkwithfastai/walkwithfastai.github.io

Re: show_results and predict, no, it won't be. This includes summary as well. Only what is shown in the notebook can I guarantee work. 

Currently it does seem like the loss function is broken due to torch bits. The solution should be to install the specific fastai version stated at the beginning of the lesson, as that is what I can guarantee it runs on.
